local Brainrots = {
	{
		name = "Tralalero Tralala",
		rarity = "Common",
		incomePerSec = 5,
		spawnWeight = 50,
	},
	{
		name = "Ta Ta Ta Ta Sahur",
		rarity = "Common",
		incomePerSec = 7,
		spawnWeight = 50,
	},
	{
		name = "Pipi Kiwi",
		rarity = "Common",
		incomePerSec = 10,
		spawnWeight = 30,
	},
	{
		name = "Lirili Larila",
		rarity = "Common",
		incomePerSec = 12,
		spawnWeight = 30,
	},
}

return Brainrots

-- Total weight = 50 + 50 + 30 + 30 = 160
	-- Tralalero: 50/160 = 31.25%
	-- Sahur: 50/160 = 31.25%
	-- Pipi Kiwi: 30/160 = 18.75%
	-- Lirili Larila: 30/160 = 18.75%